name: Build Image
on: 
  push
jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - path: flask
    steps:
      - name: Auth with registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT_DOCKER }}
      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: ./${{ matrix.path }}
          push: true
          tags: ghci.io/${{ github.repository }}:${{ matrix.path }}